

name: API Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Execute with Maven
      run: mvn clean install -Dsuite=testng -X
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: logs
        path: logs/
